baseURL = "https://techie.sahli.net/"
defaultContentLanguage = "en"
disqusShortname = "sahlinet"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-161471042-1"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "techie.sahli.net - by @philipsahli"
[author]
  gravatarEmail = "philip@sahli.net"
  homepageText = "techie.sahli.net"
  name = "Philip Sahli"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params]
  adsenseClient = 'ca-pub-3510032019858405'
  adsenseSlot = 'huhu'
  description = "A blog about Golang, Containers and Kubernetes. Posts and Questions of the Day. Made by Philip Sahli."
  licence = "[Some Rights Reserved](http://creativecommons.org/licenses/by-sa/4.0/)."
  displayPostLanguage = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.de]
    languageName = "Deutsch"
    weight = 2